#!/usr/bin/env bash
set -euf
HELP="Bashole the Bash Script Hole.
The little helper for managing those dirty collection of hacks.

Usage:
  $0 ls
  $0 <script> [<passed_through>...]

Environment Variables:
  BASHOLE_DIRECTORY		Directory containing user scripts managed by bashole, defaults to ~/.bashole
  BASHOLE_TEMPLATE		Path to copy into new scripts, defaults to a builtin sane template.
"

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SOURCE_DIRECTORY="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
source "$SOURCE_DIRECTORY/helpers.sh"

trap __cleanup EXIT
function __cleanup() {
	unset BUILTIN_DIRECTORY
}

if [ "$#" -lt 1 ]; then
	echo "$HELP"
	exit 1
else
	$(find_script_by_name "$1") "${@:2}"
fi
