#!/usr/bin/env bash
# Description: Display all available environment variables for a user script
echo
echo ENVIRONMENT WITHOUT HELPERS
echo
printenv
echo
echo ENVIRONMENT WITH HELPERS
echo
source "$BASHOLE_HELPERS"
printenv
echo
echo ARGUMENTS
echo
for var in "$@"
do
    echo "$var"
done
