#!/usr/bin/env bash
# Description: create/edit a user script, will delete it if the script is left empty
set -euf

if [ "$#" -ne 1 ]; then
	echo "Bashole subcommand usage: edit <script>"
	echo "If after the editor returns back to Bashole the script is empty it will be deleted."
	exit 1
fi
source "$BASHOLE_HELPERS"

target="$1"
target_path="$BASHOLE_DIRECTORY/$target"
template_path="$BUILTIN_DIRECTORY/../template.sh"
sane_editor="${EDITOR:-nano}"

mkdir -p "$(dirname "$target_path")"

if [ ! -f "$target_path" ]; then
	cp "$template_path" "$target_path"
	chmod +x "$target_path"
fi

"$sane_editor" "$target_path"

if ! grep -q '[^[:space:]]' < "$target_path"; then
	rm "$target_path"
elif ! maybe_shellcheck "$target_path"; then
	if get_informed_consent "re-edit file"; then
		$0 $@
	fi
fi
