#!/usr/bin/env bash
# Description: list builtin and user scripts
set -euf
GREEN='\033[0;32m'
NC='\033[0m'

function list_dir() {
	while IFS= read -r -d '' script
	do
		name="$(basename "$script")"
		desc="$(grep "^# Description" "$script" | cut -d":" -f2)"
		echo "$name	$desc"
	done < <(find "$1" -type f -executable -print0)
}

echo -e "${GREEN}Builtins:${NC}"
list_dir "$BUILTIN_DIRECTORY"
echo -e "${GREEN}User Scripts:${NC}"
list_dir "$BASHOLE_DIRECTORY"
