#!/usr/bin/env bash
# Description: rename a user script
set -euf

if [ "$#" -ne 2 ]; then
	echo "Bashole subcommand usage: rename <script_name> <new_name>"
	exit 1
fi

src="$1"
dst="$2"

mv "$BASHOLE_DIRECTORY"/{"$src","$dst"}
